### ISSUE TITLE
Simple Scrollable List

### ISSUE THREAD

**Issue by PANDAKO-GitHub** [GDevelopApp/GDevelop-extensions#105]
## Describe the extension
You can create a list with multiple items arranged vertically.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[ScrollableListExtension0.1.0.zip](https://github.com/4ian/GDevelop-extensions/files/5958257/ScrollableListExtension0.1.0.zip)

How use it: [Youtube](https://www.youtube.com/watch?v=E4Z9KlIYqrQ)
## About English translation
I'm not good at English, so please point out strange English.

**Comment by tristanbob** [comment]
This looks very useful!  Has anyone had time to test it out or review it? 

If not, we are looking for volunteers and testers!  :)

**Comment by 4ian** [comment]
I've unfortunately not the time, but it would be great to review it and rework it (for sentences, descriptions)! :)

**Comment by Midhil457** [comment]
Hi, sorry for late reviews.
I tried making a list with this extension with some help from the video, but it doesn't work for me. Sometimes the scrolling won't work, if it does, the title ,text and the icons move at a different speed. Some items not having any text added to them

So, It would be really great if you could attach a simple example that shows all the functionalities of this extension.

making it clear which item should have the list behavior can be helpful. For me, the object which had the behavior won't show up in the scene

:)

**Comment by arthuro555** [comment]
I am really conflicted with this extension, as it is a nice and useful one, but it has one big problem: It relies on the user interacting with it through a scene variable, which is [against the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#variables). 
Maybe what you can do is instead of having the user use the variable, you can make the behavior have a list id string property, and access the list via `__SSLE_Lists[Object.Behavior::PropertyID()]` instead of `ListItems`. This should allow it to be cleaner anyways as seeing the actions of the behavior, you want the array to always have the shape you want and not to be modified by the user by other means than the extension.
I would only keep the `CreateListFromJsonText`, not `CreateList`, as again the best practices are against making the user interact with an extension through variables.

Else, here are some other review points I have:
- For `RemoveItem`, the implementation is not very clean. I recommend you use the "Remove index at" action bundled with GDevelop.
- Instead of a "Repeat" event, you should use a "For each child variable" event.
- It is not that important but I would rather add a behavior property to chose if onCreated should clear the list.
- I would rename `DoStepEvent` to `Update list`.
- `SelectedSrting` is a typo -> `SelectedString`
- For AddItem I would use the GDevelop builtin function "append variable" instead
- I doubt the extension would work if I have two lists with the same objects but different lists. For example, `ClearListItems` deletes all instances of the objects used, not just the ones used by the behavior. To remedy that, I would set an objects variable with the id of the list on all objects created for that list, and then use a condition that checks for that variable with that value to only use the instances created by the behavior (like you already do with the `background` object but for `Group` instead).
- Those default return values are redundant, as GDevelop already puts those values as the default if you have not returned any: 
![image](https://user-images.githubusercontent.com/19349038/125437304-3eb845c7-1ea2-4218-bd7b-ec56aa870d98.png)
- The object variables you are using on `Object` should probably be hidden behavior properties
- The extension requires a set-up (Creating the list, updating it...), which should be described on the help URL or in the extension description. At least, even if you do not make a textual explanation, your video tutorial should be linked somewhere.


Please look into those points and update your extension, I will review it again once they have been adressed.

**Comment by arthuro555** [comment]
It's been a month without updates, I am assuming the extension has been abandoned. If the original poster does not come back and no one takes over finishing this extension, the submission will be closed in 10 days.

**Comment by PANDAKO-GitHub** [comment]
@arthuro555 Thank you for your review.
The reply is late and I'm sorry.
I thought this extension was so anomalous that it needed to be reworked.
But I have other work, so I can't fix it.
I think it's okay to close.
