### ISSUE TITLE
Update: Fix a context issue on FireBullet

### ISSUE THREAD

**Issue by D8H** [GDevelopApp/GDevelop-extensions#124]
## Describe the extension
* Give the new bullet back to the caller of the action.
* Extract the fire rate condition so actions on the new bullet that doesn't exist are not called.

This is a breaking change.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://www.dropbox.com/s/536bbz9ktacz263/FireBullet.zip?dl=1

It's used by this example: https://github.com/4ian/GDevelop/issues/2566

**Comment by arthuro555** [comment]
🤔 I wonder if we shouldn't add an action to "bubble up" the picked objects instead of using JS code, as this sounds like something that could be often useful.

**Comment by 4ian** [comment]
Yes that's a good question. I also see that currently the JS code is clearing the list of picked objects. I think this is because it needs to work like the "Create object" action, in the sense that it's not "picking" objects when called.
For this we could add a new parameter type "Object without picking" to the extensions in the editor. It actually already exists for JS/C++ extensions (see the "Create Object" action) :)

**Comment by arthuro555** [comment]
I am guessing from the conversation that this won't be added until we have a built in way to "bubble up" selected objects. Adding the tag "change required in GDevelop".

**Comment by tristanbob** [comment]
This was implemented here, so I'm closing this issue.

https://github.com/GDevelopApp/GDevelop-extensions/pull/877
