### ISSUE TITLE
Virtual joystick (nipplejs)

### ISSUE THREAD

**Issue by FlokiTV** [GDevelopApp/GDevelop-extensions#167]
# A virtual joystick for touch capable interfaces
## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6720031/Extension.zip)

https://games.gdevelop-app.com/game-9b34266e-da0a-4ca6-90dc-a57d1a53ca5f/index.html

https://github.com/FlokiTV/GDevelop-Nipple

**Comment by 4ian** [comment]
Very interesting, thanks for sharing!
The library is rendering DOM elements on top of the game canvas, not ideal but I guess this can be ok with a "DOM api" tag and an explanation.
@Bouh @arthuro555 What do you think of this? Do you want to give it a try?

**Comment by arthuro555** [comment]
Quick review:

- Please use semantic versioning for the version
- The help page URL should actually point to documentation not to the download page
- You should expose properties of the joystick via expressions not scene variables
- No need to call `runtimeScene.getVariables().add("variableName")` for each variable you use this will just cause performance loss

Additionally, I don't consider those points as as important but I think it also matters:
- Use let instead of var and for constants const instead of let
- Try to pass your code through prettier to have a more consistent style making it easier for other people to modify it
- I think it would make sense to make it a behavior, and have the object the behavior is attached to used to position the <div> used by nipplejs, kind of how I made the flex container in the flex layout extension.
- It would be nice to expose more of the options nipple js provides
- There could a memory leak as you are not destroying the nipple js manager only the container element from the DOM
- The code of nipplejs could be minimized

**Comment by FlokiTV** [comment]
Some one on my youtube channel ask me a easy way to create this, so, i just join nipplejs to a extension.
I'll make the improves @arthuro555, thanks!

**Comment by Bouh** [comment]
Is there any advancement on changes to make?
Without a new update, we'll close this submission in 10 days.

**Comment by FlokiTV** [comment]
I did it and a lot of people asked, so I did the extension. I tried to improve DOM placement to follow a sprite and get its dimensions. But GDevelop doesn't deliver scaled sprite sizes if you scale your game.

I apologize, but I don't have time to redo it.
And I lost about 60% of my eyesight recently, I need to operate a laser to fix it.

So I "disappeared" a little bit.
Thank's for your time

**Comment by arthuro555** [comment]
Don't worry about it, I hope you will be able to get your surgery without any issues. 

Do you plan to still work on this later or do you want someone else to handle the rest of the work?

**Comment by 4ian** [comment]
Good luck for your surgery @FlokiTV, I hope this will get better. 

For the extension we can take over this if needed. We can also allow this as an extension using "DOM api", even if it would be preferable if we can achieve the same without (but I understand this may be different/not as convenient to do/use).

**Comment by FlokiTV** [comment]
Yes, I've already started a new one that doesn't use DOM, just using Shape Painter.

Thanks everyone, I hope I'll be fine soon to contribute again

**Comment by Bouh** [comment]
Isn't collision on Shape Painter are limited to the default 32x32 hitbox?

**Comment by 4ian** [comment]
It is indeed. If needed we can add an option to specify the "virtual" size of the object (that will need an update in GDevelop).

**Comment by FlokiTV** [comment]
After your tips, I refactored all the code for the extension and created a new one with NippleJS.

But if the window resizes, I lose the real size of things

So I started a new extension, without NippleJS, just Shaipe painter and Javascript

https://i.imgur.com/lcQerSN.mp4

[example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7032013/example.zip)

**Comment by FlokiTV** [comment]
> It is indeed. If needed we can add an option to specify the "virtual" size of the object (that will need an update in GDevelop).

This will be nice

**Comment by DHsoftw** [comment]
For me it works ok. I had an Issue with the angles of this extension fixed by adding "-" in front of the variable angle that this extension creates

**Comment by jjhesk** [comment]
I have wrote my own joystick in full js.

**Comment by arthuro555** [comment]
Hello 👋 

In the last few months, a multitouch joystick extension has been added to GDevelop. I think that this issue can therefore be closed. If you think something could be improved with multitouch joysticks, please submit those improvements and/or new ideas as updates to that extension.

Thank you again for trying to contribute to GDevelop nonetheless!
