### ISSUE TITLE
Removes blurring of pixel text function 

### ISSUE THREAD

**Issue by Jurfix** [GDevelopApp/GDevelop-extensions#175]
## Describe the extension
This feature allows you to get rid of blurry text in low-resolution games (pixel games) without using bitmap text, for a clearer image it is recommended to choose one of the five provided fonts in the archive, font number one looks best, or choose your own font from the list of "pixel" family.
If, with your screen resolution settings and font size, the text becomes half blurred, then try choosing another font from the ones I presented in the archive or find a more suitable font on the Internet.

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[RemovesBlurringOfPixelText.zip](https://github.com/4ian/GDevelop-extensions/files/6776477/RemovesBlurringOfPixelText.zip)

**Comment by Bouh** [comment]
It was the first idea to workaround the issue with the text.
We have never added this solution because this means a big font size will produce a giant texture, that can be not supported on mobile.
For details, how works fonts and texts: when a text has to be rendered the font is parsed and a spritesheet with all characters is computed. Then this is used to display the text.

That means the font size is the real size of the characters on a sprite sheet.
This spritesheet has a dimension that is automatically measured related to the font size and scale, the spritesheet is limited.
A bigger font size means the spritesheet texture has to be larger, and there is a limit, in general 2048px maximum.

With a big font size the characters on the spritesheet can be not rendered or will be cropped, the spritesheet can sometimes be not rendered at all. So there is no text to display.

The scale is used to display the text, it resizes/rescales the spritesheet on the screen, this means the computed texture is still big in memory.

I would see this integrated into the engine, but in this case, we have to really test it and understand the limits.

**Comment by Silver-Streak** [comment]
I did some tests and yes, this behaves the same as the manual changes made to the export as listed on the forums.

This means:
If you're scaling from a large font size, it's not going to look great even with this method.
IF you're scaling from a very large font size, it won't render at all on mobile.

New to this extension:
Depending on size, it also breaks positioning.

Without the event enabled: 
![image](https://user-images.githubusercontent.com/24237149/124792934-1be07680-df13-11eb-8f98-a5426cb6f4b0.png)

WIth the event enabled one one text object, now moved to the right and almost off screen: 
![image](https://user-images.githubusercontent.com/24237149/124793066-3f0b2600-df13-11eb-921b-1a50ed563b43.png)

That said, if the positioning issue could be fixed, could there be value in it being an option with a warning on larger font sizes? Maybe. 

However, if you're using a small GAME resolution (not font size) and go to full screen even with this extension. This seems to be the majority of the times users are concerned on blurry fonts, so I'm not sure this solves that issue.

Here's the same preview as below, with fullscreen enabled (game rez 640x360, upscaled to 1080p due to fullscreen). 
![image](https://user-images.githubusercontent.com/24237149/124793449-9f01cc80-df13-11eb-9968-ee0c4197b87a.png)
You can see that the text this is applied to is still blurry.

**Comment by Jurfix** [comment]
@Silver-Streak 
640x360 game resolution, the function is applied to all texts, text 2 and 3 are not blurry, it's all about the fonts, as I wrote in the description
![image](https://user-images.githubusercontent.com/64281856/124794467-be224d80-df57-11eb-9f1c-a9d31191cfdb.png)

**Comment by Jurfix** [comment]
Large text doesn't really show up on phones, but who uses large text in a pixel platformer? Most people need text in a pixel game to display points, money, and more.

**Comment by Silver-Streak** [comment]
> 640x360 game resolution, the function is applied to all texts, text 2 and 3 are not blurry, it's all about the fonts, as I wrote in the description

So to clarify, this isn't really true. It has nothing to do with the fonts, it has to do with font placement and subpixel rendering of Canvas. Due to subpixel rendering with fonts, depending on where the text object is located at, it can appear blurry still with this method.

I've tried now with 5 different fonts and they all can be blurry depending on where they're located (and since the extension's method randomly relocates the objects, this isn't something the game dev would be able to account for).

These fonts all work fine with Bitmap Text since it doesn't use canvas text rendering and therefore doesn't have the same subpixel rendering issues, so I'm still not sure this adds a lot of value for users.  (I'm not an approver, so I'm just adding context)

**Comment by 4ian** [comment]
> These fonts all work fine with Bitmap Text since it doesn't use canvas text rendering and therefore doesn't have the same subpixel rendering issues, so I'm still not sure this adds a lot of value for users. (I'm not an approver, so I'm just adding context)

I would tend to suggest restraining to Bitmap Text when you have this "pixel perfect/no blurry text at all" requirement. I'm afraid that by pushing such workaround to users, we're making more harm than good (we now have devices crashing because the texture is too big, someone complaining about the text not rendering with font = 200, some positioning issue, etc... instead of just telling "need pixel perfect text ? use Bitmap Text. Need a flexible text ? Use Text. Yes it's blurry, it's a technical limitation").

**Comment by Jurfix** [comment]
@4ian That is, the extension will not be considered?

**Comment by Bouh** [comment]
The only good solution is to implement opentype.js in the engine, this use in input an font .tff, .oft, and create a bitmap font.
This is how works text in ct.js game engine.

**Comment by Jurfix** [comment]
It looks like it turned out to fix the offset of the text
[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6779188/Extension.zip)

**Comment by arthuro555** [comment]
Personally I am also not a big fan of this, I think bitmap text is a more viable and performant solution and should therefore be the preferred one.

**Comment by arthuro555** [comment]
Should we close this issue now considering most reviewers are against its addition?

**Comment by Bouh** [comment]
# Conclusion

- The use of the bitmap text object is recommended.
- The extension works in part, there are problems with very large font sizes.
- The use of opentype.js will fix the import of any font and will cancel the need for external files currently required on the bitmap object.
- We can't limit users to a few fonts to make it work.

I repeat the idea is commendable but it is a problem that currently has a solution via another object type.
