### ISSUE TITLE
Updated extension: Extended Math 

### ISSUE THREAD

**Issue by Jurfix** [GDevelopApp/GDevelop-extensions#177]
## Describe the extension
Integrated support for the .toFixed method, which rounds a value to a specified number of decimal places.

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[game.zip](https://github.com/4ian/GDevelop-extensions/files/6780464/game.zip)

## Extension file
[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6780454/Extension.zip)

**Comment by Silver-Streak** [comment]
So I'm not a reviewer, but thank you for updating the existing extension! That makes it more useful for everyone.

**Comment by Jurfix** [comment]
I think this method needs to be added all the way to the usual mathematical expressions, since toFixed is not related to the extended mathematics of the MATH.

**Comment by 4ian** [comment]
Thanks for submitting this. There are a couple of fixes to do:
- Can we update the description of the extension to state what this function is doing? (just writing `.toFixed` is not helping anyone who is not a JavaScript programmer).
- We would also need to have the name in PascalCase as written on this page http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- toFixed returns a **string** in JavaScript. But you declared an expression, which should return a number. This means you probably need to either parse again as a number of find a way to round with converting to a string like toFixed is doing. Otherwise this can create very nasty bugs in the game engine.
- In JS, fix the typo in `NumberOfSimbols`, use `camelCase` for JS variables, use `const` (or let) instead of var.
- Don't add a comment in JS like "Integrated by @Jurfix", instead add yourself in the author list.
- Description of parameters also need fixes ("A number of simbols after comma" => "Number of decimal places" - like you properly did in the description)

**Comment by Jurfix** [comment]
@4ian I made some changes, such as: corrected the description of the second number in the expression, changed var to let and added a unitary operator "+" to the variable that interacts with .toFixed, which should convert the string that toFixed outputs to a number, also removed comment.
[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6785792/Extension.zip)

**Comment by Bouh** [comment]
I've made changes.
- Add a new line in description.
- Add @Jurfix in author (the tagname is enough no need to put the whole URL on your github profile)
- camelCase for javascript variables
- PascalCase on function name
- Replace `+` by `Number()` => `Number(valueToBeRounded.toFixed(numberOfDecimalPlaces));`
- Use const
