### ISSUE TITLE
Animation system

### ISSUE THREAD

**Issue by VegeTato** [GDevelopApp/GDevelop-extensions#188]
![Animation system](https://user-images.githubusercontent.com/81715237/125971893-fb6415b3-e70b-442a-9f72-27fa19709f62.gif)
Animate objects
pick from a list of 31 animations
examples: squash , flying button, Pulse, Breath... etc
This extension is going to be super helpful for who don't want to spend time on animating a character/object or even a button, this extension could be used anywhere any time, it will 100% bring any kind of game to life
:sunny: BringAnyGameToLife :sunny:

**You can test the extension here:**
https://games.gdevelop-app.com/game-c509971b-2008-45ef-8de6-afda9cb984a9/index.html

-User can set the speed of the animation
-User can set the width and the height of the object
-User can set Trigger once or Not, for loop
-User can combine animations to get new effects
-Added condition to check if door is open or not for door animation
-Added condition to check if the animation has finished
**-User can pick Animation from the Animations list:**
1-**Pulse animation**
2-**Breath animation**
3-**Smooth rotation animation**
4-**Instant rotation animation**
5-**Wobble animation**
6-**Wobble2 animation**
7-**Wobble3 animation**
8-**Wobble once animation**
9-**3D rotation animation**
10-**3D rotation X animation**
11-**3D rotation Y animation**
12-**3D door loop animation**
13-**3D open door animation**
14-**3D close door animation**
15-**3D pre-closed door animation**
16-**Float animation**
17-**Triangle transition animation**
18-**Square transition animation**
19-**Rhombus transition animation**
20-**Maze transition animation**
21-**Fade loop animation**
22-**Fade out animation**
23-**Fade in animation**
24-**Squash & Stretch animation**
25-**Rainbow effect animation**
26-**Shake rotation animation**
27-**Shake horizontal animation**
28-**Shake vertical animation**
29-**Line rotation**
30-**Land animation**
31-**Low health animation**

## Checklist
- [done] Extension has a proper name and description.
- [done] Extension has tags (for example: "platform, brick, breakable").
- [done] All behaviors have a description.
- [done] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [done] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [done] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

**You can download the example here:**
[Animation system extension example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8226877/Animation.system.extension.example.zip)

**You can download the extension here:**
[Animation system extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8226878/Animation.system.extension.zip)

**Comment by tristanbob** [comment]
Woah, I didn't realize you made 31 animations!  I don't have time to review this now, but I'm looking forward to testing them eventually.

**Comment by Bouh** [comment]
I'll be reviewing it this weekend.
I like the idea of just put a behavior on the object and choose a type of animation.

**Comment by Bouh** [comment]
I made my reviews with the example project provided in the first post.

- The doors animations not working like on the GIF in the first post.

- The extension is completely managed by the events while this one fits better on behavior, the capacity of behaviors isn't exploited at their potential.
Behaviors can have properties too. The way the extension is currently made, there are none.

Maybe because there the gaps between the function possibilities and the behaviors possibilities.
Two are too different in terms of types parameters.

I suggest waiting for more types of parameters in behaviors before a new review on this extension, here we need an option list and booleans. @arthuro555  @ClementPasteau  @4ian 

- 
![image](https://user-images.githubusercontent.com/1670670/130365365-99eefe99-a6ad-45db-be10-5d7587e0ba43.png)

In the description, there is missing capitalization and period.
The long description that advice on recommended value is way too long. This should be handle in the event of each type of animation.

--------

There is the potential to have something really cool and easy to use.
For now, it's not as good as it could be because of the limitations of the engine.

**Comment by 4ian** [comment]
Boolean do work in behaviors: 
![image](https://user-images.githubusercontent.com/1280130/130435110-0f49ac2c-a74e-4b79-8007-89284947d62c.png)

But we could add support for string properties with a select field indeed 👍

**Comment by ClementPasteau** [comment]
Hey @Bouh, the option list has now been added and the boolean is already available. 
Anything else you see missing to help on this extension ?

**Comment by Bouh** [comment]
Should be ok with the new changes :)
I have to work on it and waiting for the next update before push to master.

**Comment by Bouh** [comment]
@VegeTato, I've reworked how you create the effect for a similar result with the incoming behavior property in the next release.
So I've used a nightly build to rework the first animation.

### ⚠This extension works with the latest nightly build, it won't work on the current released build (b115) ⚠
### You need for trying the extension file to [download the nightly build.](https://github.com/4ian/GDevelop/blob/master/newIDE/docs/Nightly-Builds-and-continuous-deployment.md)

The changes are:
- We drop the function in the event sheet to set up the animations, instead, we use the new property in the behaviors panel!
- You used static value for scaling the object, instead we use a property for scaling in percentage the object.
- You used a Speed property in the function without unit, instead we use a time unit in second, 1 second will complete the animation in 1 second.
- You used conditions with static values for stepping the animation, now we use object timers.
- The trigger once for animation was over-complicated, instead, see how I've done for Pulse animation.
- We keep a history of the original dimensions and angle of the object for resetting when we use trigger once property.

I've done changes only for one animation, Pulse is completely working with the changes described above.
You can see the changes in doStepPostEvents, don't care about the rest of the functions, for now, I'll do another review when the rest of the animation will works. 
So don't care about **AnimationFinished** or **DoorIsOpen**. There is the first lot of rework front of you before, reworking the function will take a few minutes to fix when the animations are complete.

All comments/groups in green are working, in red, you will see the postEvent for the wobble animation to keep at the bottom.
Just add the other animation in the group called "Groups for all animations".

I let you watch how Pulse animation has been reworked and follow the same process for the next ones.

![image](https://user-images.githubusercontent.com/1670670/131215772-10b0f002-02e3-465f-8d1d-8e56ef8188bc.png)

**Comment by Bouh** [comment]
The project file: 
[Animation system extension example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7070591/Animation.system.extension.example.zip)

**Comment by Bouh** [comment]
Since b117 is released you can continue your extension.
Maybe since you have applied the changes of the review?

**Comment by VegeTato** [comment]
> 
> 
> I'm excited for this extension to be updated and submitted. @VegeTato do you feel comfortable copying what Bouh did on "Pulse", and migrating the rest of the animations to behaviors?
> 
> If you are not available to work on this, I will try to convert at least 1 more animation this weekend.

i took a deep look at what he did and yea... i don't think i can work on this extension anymore 😅
because he changed the animations system (the math behind) and he added timers and added many variables
and new conditions and groups
not to mention its all in behaviors now.
so i got lost in there <.>
i don't know what variables goes to what nor the timers he added and the math,
so basically its much complicated for me now, if you can finish it, will be awesome <3

**Comment by D8H** [comment]
I have some suggestions about Bouh's version:
* The scale properties should probably follow the same logic as the standard action (2 = twice bigger)
  A percentage is a format not a value. One day GDevelop could allow a "Ratio (number)" property type with a customizable format in settings and if properties make pseudo formats in value directly it will break.
* The "Animation speed" property in second is actually a duration or a period.
* The dimension and angle should probably be watched to let the user change them without issues.
* The "Trigger animation once?" property should probably be something like "Play continuously".
  If I understand correctly, the animation will either play indefinitely or once at demand with an action. Because, playing it only once at the beginning of the scene doesn't make much sense.
* Using a timer is probably not a good idea as it won't be stopped when the behavior is deactivated.
  What should be the behavior in this case?
   * froze the size until activation and continue the animation (This one is probably more consistent with what other behaviors do)
   * Set back the original dimension and start from beginning at the activation
  Both features can be interesting. If we choose the 1st one, a reset action could allow to do the 2nd when needed.

The logic is probably similar to the 3D Flip extension.

**Comment by D8H** [comment]
What do you think about using the tween behavior to implement the animations to let users choose the easing function?
For the slime animation I guess that most easing function can give interesting variations.
https://easings.net/

**Comment by D8H** [comment]
I did an implementation of the Slime animation with a Tween behavior:
https://www.dropbox.com/s/67fd6w49oy2styt/Animation%20system%20extension%20example_REVIEW.zip?dl=1

I think that the events are easier to understand this way.

The issue with tween is that we can't save the dimension before scene events to watch for changes. This is a more general issue about preEvent or postEvent call order: there is no way to choose which behavior is processed first.

**Comment by tristanbob** [comment]
First, I want to say thanks to everyone who has worked on this so far.  I really appreciate having a team to bounce ideas and improve each other's work. 

Second, I apologize for not spending more time reviewing this.  Hopefully, we can get the ball rolling again! (see, it's an animation pun).  :)

> * The scale properties should probably follow the same logic as the standard action (2 = twice bigger)
>   A percentage is a format not a value. One day GDevelop could allow a "Ratio (number)" property type with a customizable format in settings and if properties make pseudo formats in value directly it will break.

I agree, using scale is much more flexible than using pixels.

> * The "Animation speed" property in second is actually a duration or a period.

Yes, using seconds to complete the animation is MUCH more user-friendly.  Game creators need to know how long the animation will take. 

>   * freeze the size until activation and continue the animation (This one is probably more consistent with what other behaviors do)
>   * Set back the original dimension and start from beginning at the activation
>     Both features can be interesting. If we choose the 1st one, a reset action could allow to do the 2nd when needed.

I like the idea of allowing both a "pause", and a "reset to original values" option.

### Current thoughts:

I really like the idea of migrating to using tweens for this extension:
1.  Using Tweens gives users a LOT of flexibility in how an animation moves
2.  Tweens also handle time well

I will take another stab at converting one of these animations, this time using @D8H Tween method.

**Comment by tristanbob** [comment]
### Question: How should we organize the multiple animations?  

Here are some options:

1) Create a separate behavior for each animation
- Benefit is that each behavior will have its own properties and can be run simultaneously
- Negative outcome is that this option has the most duplication of code

2) One behavior with a monolithic action to start them (currently used by this animation)
- Least duplication of code
- Also least flexibility because the action cannot include all unique parameters without being ridiculous to use  
- Animations will share properties so possible for animations to interfere with each other

3) One behavior with unique actions to start each one (this is what I am proposing for TransitionPainter extension)
- Hybrid of the two previous options.  Less code re-use, and good flexibility.  
- Behavior will have a long list of properties, some that will only be used by one animation, some that will be shared.

I'm not confident that #3 is the best option.  What do you guys think?  Are there other options to manage these animations?

**Comment by arthuro555** [comment]
I'd prefer option 1 personally. I think duplication of code can always be avoided by making private extension functions? If every animation has some similar base code, you could also make a base "Animation System" behavior that handles all the common code, and have all behaviors for the individual animations require that base behavior. I don't really have the time right now to look into the extension myself to tell if that's really a good solution or not, so take that with a pinch of salt 😬

**Comment by VegeTato** [comment]
1- this looks smooth and friendly honestly, even tho there will be a lot of duplication codes, still this is how i built it anyway if you take a closer look, a lot of duplication are already in there and working fine, it just takes time

2- yea its not very user friendly and have many problems with the parameters for each animation

3-a lot of parameters wont share the same properties because each animation have its own settings and only few share the same properties like (speed)

in my opinion **1** is the best option for this reasons:
1-Very friendly and easy to use
2-Every animation will have its own properties without any issues
3-dpulication codes always have a workaround like what arthuro mentioned above, if not, still can duplicate codes it just takes time to finish but the outcome will be a perfect extension

Thanks for your time reviewing the extension tho ❤️ 
and for everyone who reviewed the extension ❤️ 
together we can make it perfect ❤️

**Comment by tristanbob** [comment]
@D8H or @Bouh do you have any thoughts on how to organize this extension?  

I think whichever strategy we decide for this extension, is also what I will do on the transition painter.  It is similar because they both provide a lot of different animations in a single extension, which can be unwieldy to maintain if we are not careful.

**Comment by Bouh** [comment]
One behavior per animation is fine and as you said the organization will be better.
And yes no need to duplicate the events, private functions are useful to reused shared events, like for the speed, scale, etc...

**Comment by tristanbob** [comment]
Thanks for the input, everyone!

I am going to try implementing one animation (Pulse) with helper functions as needed, with the idea that each animaton will be converted into it's own extension (probably by first copy/pasting this one).

**Comment by D8H** [comment]
Please, don't reopen this issue and continue the discussion on the PR: https://github.com/GDevelopApp/GDevelop-extensions/pull/378

Reopening it make it visible in the review board and reviewer will confused it with a PR, modify it (like I did) and it creates automatic PR.
