### ISSUE TITLE
Boomerang

### ISSUE THREAD

**Issue by Entr0py404** [GDevelopApp/GDevelop-extensions#194]
## Describe the extension
Boomerang launches an object that returns to the thrower after a specified amount of time.
![CiXaeLwWkg](https://user-images.githubusercontent.com/75917656/127251352-83cb85a1-b8f6-467a-8911-952c11647beb.gif)

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[Boomerang Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889759/Boomerang.Extension.Example.zip)

## Extension file
[Boomerang.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889762/Boomerang.zip)

**Comment by tristanbob** [comment]
@Entr0py404 great job on this one!  I am also looking forward to some of the other extensions you have shared.  :)

## Version 0.9.0

- Made minor logic changes, wording, and cleaned things up
- Added mouse input to example game and showed boomerang passing through an enemy

## Extension file

[ThrowBoomerangExtension_0.9.0.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7026408/ThrowBoomerangExtension_0.9.0.json.zip)

## Playable game

https://games.gdevelop-app.com/game-5afb1050-e5a2-497b-8bf4-ae2bdfbcf237/index.html

## Example game folder

[Boomerang Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7026406/Boomerang.Extension.Example.zip)

## Video

https://user-images.githubusercontent.com/8879811/130338697-bb401fa7-9ad9-46b8-a8a5-896eeb7f775a.mp4

**Comment by 4ian** [comment]
Awesome, thanks both this looks super great!
Very minor nitpickings:
- You can remove the first event here:
  ![image](https://user-images.githubusercontent.com/1280130/130362953-edff85ef-98e3-4375-a140-1a3a665368f6.png)
  By convention, the return value of a condition is false if not set.
- ThrowBoomerangAngle/ThrowBoomerangPosition => no period at the end of a sentence in the events sheet by convention
- Behavior description => period at the end of the description ;) 

And a more important one:
- The name: "Throw Boomerang". Shouldn't this be just "Boomerang"? Because you add the behavior to the "Boomerang object", not to the object that will throw the boomerang.

Apart from that, looks good to go! :)

**Comment by tristanbob** [comment]
## Version 1.0.0

I have made the changes you mentioned.

## Extension file

[BoomerangExtension_1.0.0.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7036370/BoomerangExtension_1.0.0.json.zip)

**Comment by 4ian** [comment]
Awesome! I've added it :) Thanks both, great extension!
