### ISSUE TITLE
Updated for YandexGamesSDK extension

### ISSUE THREAD

**Issue by achubutkin** [GDevelopApp/GDevelop-extensions#215]
## Describe the extension
An extension for Yandex.Games SDK that lets you easily integrate games created by GDevelop into the Yandex.Games platform.

**Attention! The update for earlier Yandex.Games SDK extension (by own) to the non-compatible next version.**

An extension for Yandex.Games SDK that lets you easily integrate games created by GDevelop into the Yandex.Games platform. The extension provides the following features:

* Set up automatic switching to full screen mode
* Set up screen orientation during the game and add a rotate device prompt
* In-game purchases
* Player details (user login, in-game data, user profile data)
* Game rating
* Manage ads (interstitial ad, rewarded videos)
* Competition tables 

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

[Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7148026/Extension.zip)

**Comment by achubutkin** [comment]
Hey! Please be informed that the archive with the extension in the attachment has been updated. Sorry for such an update, I forgot to change the extension ID for the conditions inside the extension.

**Comment by Bouh** [comment]
- ![image](https://user-images.githubusercontent.com/1670670/132961378-b6f07365-73a1-4333-9958-bb12429209b3.png)
Instead of polluate the window scope with private variables you can directly store the values in extension namespace.

`gdjs._YandexGamesSDK.variables = { ... )`

- Is this extension has been already used for a game?
- `var` is used everywhere, you must use `const` for static variables

Otherwise lgtm :+1:

**Comment by achubutkin** [comment]
[Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7149107/Extension.zip)
@Bouh Many thanks for your review! It`s done. Please, see an attachment. 

- replaced var to const/let (here depend from a situation)
- replaced window scope to the extension namespace

**Comment by Bouh** [comment]
- Did you know if the previous version of this extension can be still used or if the Yandex API has completely changed that makes the previous version completely outdated and useless?
- If the previous version can be still used, and because this one containt breacking change, what you think to rename the updated extension to `Yandex Game SDK v2` for kept two extension v1 and v2 in the extension list?

**Comment by achubutkin** [comment]
I thinking about to save both versions. But the old v1 version not supported in more from Yandex side (no new features like in v2 version). And the old extension contains only 2 actions. This is not so much, and after the updates, I hope the developers will correct their actions and conditions.

**Comment by Bouh** [comment]
Ok, then, we go for keep only one extension with the previous actions mark as "outdated" in the action name.
This doesn't break the compatibility for older games, we have just one extension, and developers will see the new actions and correct their games.

**Comment by achubutkin** [comment]
@Bouh Good!

**Comment by Bouh** [comment]
Added in https://github.com/GDevelopApp/GDevelop-extensions/commit/a6d9d41ebd2a72274a44448f563c22ce04c51314
Thank you!
