### ISSUE TITLE
Game Jolt API

### ISSUE THREAD

**Issue by MauryDev** [GDevelopApp/GDevelop-extensions#27]
**Name**
Game Jolt API

**Description**
This version is beta, so there may be errors in the requests.

There are functions for Scores, Data Store, Time, Session, Users, Friends and Trophies and others tools.

[game-jolt-api.zip](https://github.com/4ian/GDevelop-extensions/files/3958447/game-jolt-api.zip)

**Comment by 4ian** [comment]
Nice :) 
A few feedbacks based on what I've seen: 
* You're loading a library from "https://maurydev.github.io/game-jolt-api-gdevelop/lib/versions/1.0.1/index.min.js", can you describe what is it?
* Remember that if you're using fat arrow functions (`(name) => ...`) instead of `function`, you're breaking compatibility with Android 4.4. (I've added a card on the roadmap to automate the detection of this: https://trello.com/c/DRaJS0hY/385-add-warning-when-adding-extension-or-when-the-game-is-exported-about-android-4-compatibility and warn the users)
* You're using `eval`, why doing so? It's dangerous as it can let arbitrary code being executed. Can you explain why you're using it or remove it? In 99.9% of the case, there is a better way to do it using safer JavaScript functions.

**Comment by MauryDev** [comment]
1- I didn't want to write so much code in the project, so I made an external file.

I made the code smaller and more unreadable to read.

2- I did not know that some platforms did not support `() =>`

3- I will correct the eval, I also found it.

My repository: https://github.com/MauryDev/game-jolt-api-gdevelop

**Comment by 4ian** [comment]
> My repository: https://github.com/MauryDev/game-jolt-api-gdevelop

That's good work! :) 
Right now GDevelop miss the ability to embed an external library like the one you did. 

Nevertheless, it could be interesting to bundle the content of the index.min.js into the extension itself (as a JavaScript event that is called when you initialise the extension maybe?). So that players don't have to download another file from github when running the game (it's more robust and secure) :)

**Comment by MauryDev** [comment]
Update :v

[game-jolt-api.zip](https://github.com/4ian/GDevelop-extensions/files/3961784/game-jolt-api.zip)

**Comment by 4ian** [comment]
Cool! :) 
Thanks for including the whole library in the extension 👍 You can still include a comment with a link to your Git repository if you wish?

No eval seems better :) I'll take a more in depth look tomorrow.

Thanks for working on this! Will be very useful 👍

**Comment by MauryDev** [comment]
Git repository: https://github.com/MauryDev/game-jolt-api-gdevelop.git

Any mistake or good thing I mentioned.

**Comment by 4ian** [comment]
Thanks this looks very complete :) 
I've started to go through descriptions of actions and make some fixes.
For example, sentences of actions like `"Response Trophies. Message ID: _PARAM1_,Variable Data: _PARAM2_"` should instead be full sentences, like `Save all trophies from Message ID _PARAM1_ into scene variable _PARAM2_`

Other things to fix:
* You mention global variables while it's scene variables.
* Can you explain what Message ID is?

I'll go through everything and try to fix the mistakes/improve the sentences :) Thanks for this very complete implementation so far.

**Comment by MauryDev** [comment]
Message ID: Name of the variable that receives the api response that is different from the scene variable, global variable, and object variable.

I don't speak much English. I am taking a free online course.

And the global variable I did wrong.

**Comment by 4ian** [comment]
> I don't speak much English. I am taking a free online course.

That's a great job you've done considering this :)

I'll go and fix the extension in the next days and will publish it.

**Comment by 4ian** [comment]
I've seen that some parameters have a long description. I'll be making changes to GDevelop so that we can put long descriptions below the fields in the interface, so that it's not taking too much space on the field itself. See this: https://trello.com/c/ZzQI6giY/389-add-support-for-long-descriptions-for-action-conditions-parameters-shown-as-helper-text-below-the-parameter-field

**Comment by MauryDev** [comment]
Would be great. I wish I could add icon for extension.

**Comment by 4ian** [comment]
If you have an icon post it here and I'll see if I can add it later when extension support icons

**Comment by MauryDev** [comment]
![0](https://user-images.githubusercontent.com/41791247/71277989-1faea700-2335-11ea-8aac-b420e7d373f7.png)

**Comment by derric-young** [comment]
about messege id how do u use it

**Comment by derric-young** [comment]
quit

**Comment by arthuro555** [comment]
What is the change required in GDevelop here, icons or javascript based extensions? If it is the former the process can be resumed. If not, for the record, I had made an extension around the same time as MauryDev for game jolt that didn't load any external script.
[Here is the file](https://github.com/4ian/GDevelop-extensions/files/6735586/gjext.zip), though I do not remember at all how I did it and haven't taken a new look at it so the code quality may be very bad and it may be incomplete.

**Comment by arthuro555** [comment]
If there are no updates in the next 10 days, I will consider this abandoned and close the issue.

**Comment by derric-young** [comment]
the change i dont know what needs to be changed mabie the message id or something else altho arthuro555 did make a gamejolt api extention for gdevelop and should be intergraited into gdevlop itself. another thing that needs to be changed is the way extentions get their icons as for some resean it considered malware or virus

**Comment by arthuro555** [comment]
My version of the extension is old and incomplete. I would rather redo it with GDevelop events rather than JavaScript. I also am not sure what the needed changes are hence why I don't do them myself but ask the original author to tell if they plan to do it or if we should just make a new one.

**Comment by DerpChest** [comment]
Trying to use this Softlocks my game.

**Comment by 4ian** [comment]
This extension is sadly abandoned and should probably not be used. If someone needs the GameJolt API, a brand new extension should be started from scratch.

**Comment by arthuro555** [comment]
I'll close this and add it in extensions ideas on Trello then.

**Comment by derric-young** [comment]
huh
