### ISSUE TITLE
New extension: Idle object tracker.

### ISSUE THREAD

**Issue by 4ian** [GDevelopApp/GDevelop-extensions#314]
### Description

Update to the Idle object tracker extension.

### How to use the extension

Update to the Idle object tracker extension.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[Game example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7656579/Game.example.zip)

### Extension file

[IdleTracker.json 2.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7656580/IdleTracker.json.2.zip)

**Comment by 4ian** [comment]
@arthuro555 Any idea why the bot is opening two PRs? 🤔

**Comment by arthuro555** [comment]
Oh it seems to be receiving the opening of the PR and the addition of the new extension label as 2 events causing it to be triggered twice... Both run in parallel, so normally one opens a PR, and the other see that there is a PR already existing and aborts, but since both run in parallel, there is a race condition that allows this to be done twice. We can fix that by not listening on the issue opened event anymore, since the labeled one is also applied on creation.

**Comment by 4ian** [comment]
I see! We can maybe keep only the label then (that would allow to trigger the workflow on issue only when we want, which is also interesting).
Seems that also I had a PR created with the example rather than the extension JSON, because the extension JSON was not finished uploading.. Anyway no big deal, it's working overall!

I wonder if one day we could entirely automate the publishing directly from the editor! Maybe we could make an API to open issue/PRs with the files directly from the editor.

**Comment by arthuro555** [comment]
> I wonder if one day we could entirely automate the publishing directly from the editor

Probably, though I don't think I'd be able to do that as it would require some backend code (either for the GitHub oauth redirect if we use the user's account or to keep the bot's credentials secret if we use a bot account)
