### ISSUE TITLE
New extension: Selection Outline

### ISSUE THREAD

**Issue by FerbFloo** [GDevelopApp/GDevelop-extensions#393]
### Description

This extension adds a very small action, that automises a task I found myself using quite a lot, especially when creating menus: It allowes the user to set two outline colors for a BBCode Text Object, one that will show whenever the mouse is hovering over it and one that shows whenever it is not. This helps a lot to quickly give menus/UI a bit of feedback. Though it is only a really simple task, it tends to clutter up event sheets, especially when used on multiple text objects at once.

### How to use the extension

Add the behaviour "SelectionOutline" to a BBCode Text and then add the according action to your event sheet. Specify the object, color when hovered, color when not hovered and text you wish that instance to display.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

https://drive.google.com/file/d/1m2e_vTUiSeX81gfps1dQJgThsj5jlM6z/view?usp=sharing

### Extension file

https://drive.google.com/file/d/1rNGQkDh5lgMy5aft2aQy4mje-VycHgB1/view?usp=sharing

**Comment by arthuro555** [comment]
Hello 👋 

Please do not put a google drive link, instead, drag and drop your extension zip file into the github text editor box to upload it to github. Otherwise our automated tests will not be able to run on your extension and allow it to be submitted.

---

Your extension has been marked for review, but a new option has presented itself in the meantime. We now have a list of unreviewed "Community extensions", and your extension can be added to it, bypassing the review phase.

If you chose to *not take a review*, you need to keep the following in mind:

- As of now, community extensions are not yet shown to users, but they should be until next update
- Community extensions will never be shown to GDevelop users directly, they will have to check a checkbox for them to be shown
- All community extension have a warning about them being unstable and unreviewed displayed on their store page
- Your extension will be added immediately, no question asked, and without you needing to do any changes to your extension
- You will still need to make an extension that passes the bot's tests (meaning you still should respect the extension best practices)

tl;dr You will not need to do any more (or only minimal) work on your extension, but it might not meet the standards of all users, and reach less users.

If you chose to continue on with the review:

- The reviewing process might require of you to make some changes to your extension until it meets our reviewer's standards
- Your extension will reach more users
- You will be delivering a better extension to the community
- It will take a bit more time for your extension to be added to the store

tl;dr You will need to do a bit more work but deliver a high quality contribution that will reach more people


The choice is yours, please tell us how you would like to continue.
