### ISSUE TITLE
Creffy Asset Tool

### ISSUE THREAD

**Issue by craftersshaft** [GDevelopApp/GDevelop-extensions#67]
## Describe the extension
Load image assets from urls and make new animations for sprites. Useful for modding/loading an asset from a master server.
## Checklist

- [ye] Extension has a proper name and description.
- [yep, dont know if i need more though] Extension has tags (for example: "platform, brick, breakable").
- [yeah] All behaviors have a description.
- [yes] All functions (actions, conditions, expressions) have descriptions.
- [go for it] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
(had to zip it, but should be the only file in there)
[CreffyAssetTool101.zip](https://github.com/4ian/GDevelop-extensions/files/5563423/CreffyAssetTool101.zip)

Finally, attach the .json file of your extension here.

**Comment by craftersshaft** [comment]
[CreffyAssetTool11.zip](https://github.com/4ian/GDevelop-extensions/files/5563927/CreffyAssetTool11.zip)
accidentally broke something last version, this one also adds audio loading support

**Comment by craftersshaft** [comment]
[CreffyAssetTool14.zip](https://github.com/4ian/GDevelop-extensions/files/5580759/CreffyAssetTool14.zip)
The Slightly Better One

**Comment by arthuro555** [comment]
Sorry for the late review. I have taken a look and while this extension is very interesting it is... very hacky.
First of all, I am against the inclusion of all methods that modify the project data. This is supposed to show the initial static state of the game, and should not be mutated while it is running. Instead, change the running instances.
Second, you shouldn't use properties that begin with an underscore, especially not exclusively. Those are implementation details and may change breaking your code at any time. Instead, use the methods which are public API.
And last, the naming is not perfect. Let's say that naming a play sound action that only differs in accepting a string expression instead of a resource "Play sound deluxe" isn't great. The users won't know what the purpose is or what it does from this name. Instead you could use standard naming, for example like in the key pressed action: 
![image](https://user-images.githubusercontent.com/19349038/124830287-f175d400-df79-11eb-8f86-618179fbacb6.png)


Generally I think this extension also needs to be more focused instead of doing 20 things at a time. Not to say what it does isn't useful, it is and can be very interesting, but you should probably separate different things in different extensions.

**Comment by arthuro555** [comment]
If there are no updates in the next 10 days, I will consider this abandoned and close the issue.

**Comment by craftersshaft** [comment]
realized i basically also abandoned this besides multiple tiny updates, but yeah i'll probably resubmit if i ever split these up into better worded things.
[CreffyAssetTool143.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6797627/CreffyAssetTool143.zip)
