### ISSUE TITLE
Mobile In-App Purchase using old version of Google Play Billing.

### ISSUE THREAD

**Issue by ForFun92** [GDevelopApp/GDevelop-extensions#983]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

Mobile In-App Purchase

### Describe the bug of the extension

Mobile In-App Purchase Version 0.0.2 (Extension) using old version of Google Play Billing. By 1 November 2023 , must use Billing Library version 5 or newer. 
I don't know how I could update by my self this extension to meet the requirements, so please help and update.

### Steps to reproduce

<img width="994" alt="Screenshot 2023-07-12 at 18 14 58" src="https://github.com/GDevelopApp/GDevelop-extensions/assets/141330160/1dae6a22-e33b-4d4a-af22-4811ee42ec89">

### GDevelop platform

Desktop

### GDevelop version

5.2.169 

### Platform info

Device (For Mobile)
App Store Google Play 

### Additional context

or please advise how I can update the version myself if not beyond my abilities.

Thank you very much

with respect

KW92

**Comment by Bouh** [comment]
It require to update the cordova package used in this extension, [cordova-plugin-purchase ](https://www.npmjs.com/package/cordova-plugin-purchase) from v11 to 13.6.0

![image](https://github.com/GDevelopApp/GDevelop-extensions/assets/1670670/50c46714-49bd-4b03-bd50-0c9db26fb481)


There is a guide to read to update the code with the new requirement of this extension.
[Read the migration guide to V13.6.0.](https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13)

Then:
- Make a new export of a game using the update v13.6.0.
- Check all the functions in a game pushed on the Google Store. There is an [project example for it if needed.](https://gdevelop.io/game-example/in-app-purchase)
Because just testing in GDevelop in preview won't be enough to check the Google services the app need to be exported for android.

**Comment by ForFun92** [comment]
*I am very grateful thank you 😊 *

[image: Screenshot 2023-08-23 at 13.23.04.png]

*I have one more question, is there a simple solution to this problem? ☝ *


*I have no idea what a deobfuscation file is 😅*

Have a nice day 😉

Kamil

**Comment by Bouh** [comment]
I don't know much about this, [I found a video that explain the problem and a solution](https://youtu.be/OGo-h3uanzA).

But GDevelop doesn't provide the require file to map the stack traces.

**Comment by 4ian** [comment]
The de-obfuscation files are not related to this extension and this is a warning that is *completely unrelated* to the, real, issue (which is: updating to Google Play Billing library v5, which can be done by upgrading cordova-plugin-purchase and doing the adaptations explained in the previously shared links).

This extension should be updated for this, any help is welcome.

**Comment by tristanbob** [comment]
This has been fixed here: https://github.com/GDevelopApp/GDevelop-extensions/pull/1017
